<h2> The Principle of Effective Demand </h2>

<h3>I</h3>
<p>WE need, to start with, a few terms which will be defined precisely later. In a given state of technique, resources and costs, the employment of a given volume of labour by an entrepreneur involves him in two kinds of expense: first of all, the amounts which he pays out to the factors of production (exclusive of other entrepreneurs) for their current services, which we shall call the factor cost of the employment in question; and secondly, the amounts which he pays out to other entrepreneurs for what he has to purchase from them together with the sacrifice which he incurs by employing the equipment instead of leaving it idle, which we shall call the user cost of the employment in question.[1] The excess of the value of the resulting output over the sum of its factor cost and its user cost is the profit or, it we shall call it, the income of the entrepreneur. The factor cost is, of course, the same thing, looked at from the point of view of the entrepreneur, as what the factors of production regard as their income. Thus the factor cost and the entrepreneur’s profit make up, between them, what we shall define as the total income resulting from the employment given by the entrepreneur. The entrepreneur’s profit thus defined is, as it should be, the quantity which he endeavours to maximise when he is deciding what amount, of employment to offer. It is sometimes convenient, when we are looking at it from the entrepreneur’s standpoint, to call the aggregate income (i.e. factor cost plus profit) resulting from a given amount of employment the proceeds of that employment. On the other hand, the aggregate supply price[2] of the output of a given amount of employment is the expectation of proceeds which will just make it worth the while of the entrepreneurs to give that employment.[3]

<p>It follows that in a given situation of technique, resources and factor cost per unit of employment, the amount of employment, both in each individual firm and industry and in the aggregate, depends on the amount of the proceeds which the entrepreneurs expect to receive from the corresponding output.[4] For entrepreneurs will endeavour to fix the amount of employment at the level which they expect to maximise the excess of the proceeds over the factor cost.

<p>Let Z be the aggregate supply price of the output from employing N men, the relationship between Z and N being written Z = φ(N), which can be called the Aggregate Supply Function.[5] Similarly, let D be the proceeds which entrepreneurs expect to receive from the employment of N men, the relationship between D and N being written D = f(N), which can be called the Aggregate Demand Function.

<p>Now if for a given value of N the expected proceeds are greater than the aggregate supply price, i.e. if D is greater than Z, there will be an incentive to entrepreneurs to increase employment beyond N and, if necessary, to raise costs by competing with one another for the factors of production, up to the value of N for which Z has become equal to D. Thus the volume of employment is given by the point of intersection between the aggregate demand function and the aggregate supply function; for it is at this point that the entrepreneurs’ expectation of profits will be maximised. The value of D at the point of the aggregate demand function, where it is intersected by the aggregate supply function, will be called the effective demand. Since this is the substance of the General Theory of Employment, which it will be our object to expound, the succeeding chapters will be largely occupied with examining the various factors upon which these two functions depend.

<p>The classical doctrine, on the other hand, which used to be expressed categorically in the statement that “Supply creates its own Demand” and continues to underlie all orthodox economic theory, involves a special assumption as to the relationship between these two functions. For “Supply creates its own Demand” must mean that f(N) and φ(N) are equal for all values of N, i.e. for all levels of output and employment; and that when there is an increase in Z( = f(N)) corresponding to an increase in N, D( =f(N)) necessarily increases by the same amount as Z. The classical theory assumes, in other words, that the aggregate demand price (or proceeds) always accommodates itself to the aggregate supply price; so that, whatever the value of N may be, the proceeds D assume a value equal to the aggregate supply price Z which corresponds to N. That is to say, effective demand, instead of having a unique equilibrium value, is an infinite range of values all equally admissible; and the amount of employment is indeterminate except in so far as the marginal disutility of labour sets an upper limit.

<p>If this were true, competition between entrepreneurs would always lead to an expansion of employment up to the point at which the supply of output as a whole ceases to be elastic, i.e. where a further increase in the value of the effective demand will no longer be accompanied by any increase in output. Evidently this amounts to the same thing as full employment. In the previous chapter we have given a definition of full employment in terms of the behaviour of labour. An alternative, though equivalent, criterion is that at which we have now arrived, namely a situation, in which aggregate employment is inelastic in response to an increase in the effective demand for its output. Thus Say’s law, that the aggregate demand price of output as a whole is equal to its aggregate supply price for all volumes of output, is equivalent to the proposition that there is no obstacle to full employment. If, however, this is not the true law relating the aggregate demand and supply functions, there is a vitally important chapter of economic theory which remains to be written and without which all discussions concerning the volume of aggregate employment are futile.